[Settings]
Priority=Default
Properties=MyCustomProperty

[Default]
OSInstall=Y
SkipAdminPassword=YES
AdminPassword=Ultron@AutoBench2026!

; Desativação completa de telas interativas do MDT (Zero-Touch puro)
SkipBDDWelcome=YES
SkipDeploymentType=YES
DeploymentType=NEWCOMPUTER
SkipComputerName=YES
OSDComputerName=LAB-%SerialNumber%
SkipDomainMembership=YES
JoinWorkgroup=WORKGROUP
SkipUserData=YES
SkipLocaleSelection=YES
KeyboardLocale=0416:00000416
UserLocale=pt-BR
UILanguage=pt-BR
SkipTimeZone=YES
TimeZoneName=E. South America Standard Time
SkipApplications=YES
SkipCapture=YES
SkipBitLocker=YES
SkipSummary=YES
SkipFinalSummary=YES
FinishAction=RESTART

; Configuração de Rede e Logs
EventService=http://192.168.57.43:7000
SLShare=\\192.168.57.87\DeploymentShare$\Logs
WSUSServer=
